version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/study-app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
